### PR TITLE
Setup express server

### LINKED ISSUE #8: Setup Express server

### PR DESCRIPTION
**Pull request by martomi**
Close #8

### CODE REVIEW

**Review by lustoykov — APPROVED** [review]
Good!

**Comment by chaoran-chen** [comment]
Nice setup, @martomi! Just a small question: in README.md, you've written

> You can also:
> Import and save files from GitHub, Dropbox, Google Drive and One Drive
> Drag and drop markdown and HTML files into Dillinger
> Export documents as Markdown, HTML and PDF

What does it mean?

**Comment by lustoykov** [comment]
@martomi caught into copy-paste 🤣?

**Comment by martomi** [comment]
Yes, indeed. I saw it too and will remove it when I fix the conflict with develop.
I'm using http://dillinger.io for markdown editor (which is really nice), but since I didn't clear the example text to keep it as syntax reference I ended up copying some of it.

**Pull request merged**
