### PR TITLE
Update README.md

### LINKED ISSUE #27: Host the Website
Make the code run on Heroku or similar hosting services.

### PR DESCRIPTION
**Pull request by chaoran-chen**
A simple Ubuntu virtual machine was set up using AWS EC2. It pulls the repository and starts the service using docker-compose. For integrating updates, the repository has to be fetched and docker to be restarted manually.

Closes #27

### CODE REVIEW

**Review by kordianbruck — APPROVED** [review]
Fine for now. I will work something out with @sacdallago for the future

**Comment by sacdallago** [comment]
Interesting. Can you explain how you did it? Do you have to manually _deploy_ the machine (`docker run xyz`) or have you set up some automatic _deployment_ strategy?

I'm talking deployment, not build! :)

My idea would be:

1. Automatic builds with docker hub
2. Automatic deploy with docker cloud

And for the docker cloud _node_, we use a VM I have there lying!

**Comment by chaoran-chen** [comment]
We have an automatic build on docker hub, but currently, I'm not using it for this machine.

I've pulled the Github repository in the virtual machine and built it (`npm install & npm run build`). Then, I've run `docker-compose` in a screen.

We could certainly improve the setup - should we? Or are you going to set up a productive system for the total project anyway?

**Comment by sacdallago** [comment]
@chaoran-chen the latter! Ideally everything will be fetched from docker hub automatically on a new built, otherwise someone will have to re-deploy every time there is a new built or something like that. I thought of going through this during the presentation days, you solution can work for now but please keep it as a very **experimental** thing.

**Comment by chaoran-chen** [comment]
Great! Then, we can keep our focus on coding. Our plan is to finish our current open issues until next week so that we can show some real visualization components in the presentation.

**Pull request merged**
