### PR TITLE
Add a prototype of the relationship exploration widget

### PR DESCRIPTION
**Pull request by chaoran-chen**
Addressing #56, I've created a tiny prototype. Here is an online demo: http://54.68.164.199:8084/relations_exploring_table/

Important functionalities that are missing:
* The remaining part of the shortened sentences should be displayed in a tooltip when hovering over them.
* When a user clicks on a box, it should be filtered. The filter will be displayed right under the search box and can be removed by clicking on the filter.

table

What do you think, @MusicConnectionMachine/jstech?

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Ping @vviro. Is it a viable approach for you?

**Comment by chaoran-chen** [comment]
Since nobody wants to comment on this and we have a good approach in #61, I guess that this proposal will not be realized. But I think that we should still merge and store it in our collection of experiments because this solution (in contrast to #61) is able to handle data with varying _subjects_ (cf., https://github.com/MusicConnectionMachine/VisualizationG5/issues/56#issuecomment-292724386). Thus, if it should turn out that the majority of data tuples have a different _subject_ than the actual "main entity" and that the data groups are not able to [transform the data](https://github.com/MusicConnectionMachine/VisualizationG5/issues/56#issuecomment-292725486), this prototype could be useful as the basis of a respective widget.

@martomi 
@lustoykov 
@Binabiko

**Comment by joern-vh** [comment]
I like this approach very much. Storing in Experiments for later is a good idea 👍🏼

**Review by lustoykov — APPROVED** [review]
let's merge it then

**Pull request merged**
